
//创建房间模态框

export const CREATE_BUILDING_START = 'CREATE_BUILDING/START'
export const CREATE_BUILDING_SUCCESS = 'CREATE_BUILDING/SUCCESS'
export const CREATE_BUILDING_FAILURE = 'CREATE_BUILDING/FAILURE'
