//action类型,习惯用法 'type/'+type ，避免action类型冲突

export const POST_MODIFY_START = 'MODIFY/POST_START'
export const POST_MODIFY_SUCCESS = 'MODIFY/POST_SUCCESS'
export const POST_MODIFY_FAILURE = 'MODIFY/POST_FAILURE'

export const FETCH_MODIFY_START = 'MODIFY_INFO/FETCH_START'
export const FETCH_MODIFY_SUCCESS = 'MODIFY_INFO/FETCH_SUCCESS'
export const FETCH_MODIFY_FAILURE = 'MODIFY_INFO/FETCH_FAILURE'