//action类型,习惯用法 'type/'+type ，避免action类型冲突

export const FETCH_STARTED_ALL = 'CASCARDER/FETCH_STARTED_ALL';
export const FETCH_SUCCESS_ALL = 'CASCARDER/FETCH_SUCCESS_ALL';
export const FETCH_FAILURE_ALL = 'CASCARDER/FETCH_FAILURE_ALL';

export const FETCH_STARTED_PROJECT = 'CASCARDER/FETCH_STARTED_PROJECT';
export const FETCH_SUCCESS_PROJECT = 'CASCARDER/FETCH_SUCCESS_PROJECT';
export const FETCH_FAILURE_PROJECT = 'CASCARDER/FETCH_FAILURE_PROJECT';
export const ORZ_PROJECT_SELECT_ARR = 'CASCARDER/PROJECT_SELECT_ARR';